Source/MobileService/Controllers/ContactsController.cs
namespace MobileService.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class ContactsController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Source/MobileService/Controllers/LogoutController.cs
namespace MobileService.Controllers
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authentication;
    using Microsoft.AspNetCore.Mvc;

    public class LogoutController : Controller
    {
        public async Task<IActionResult> Index()
        {
            await HttpContext.SignOutAsync();

            return RedirectToAction("Index", "Home");
        }
    }
}

Source/MobileService/Controllers/OrderController.cs
namespace MobileService.Controllers
{
    using System;
    using System.Security.Claims;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;

    using AutoMapper;

    using ViewModels.Order;
    using Services.Contracts;
    using Services.Models.Order;

    public class OrderController : Controller
    {
        private readonly IMapper mapper;
        private readonly IOrderService orderService;
        private readonly IDeviceService deviceService;
        private readonly IRepairService repairService;
        private readonly IEmployeeService employeeService;

        public OrderController(
            IMapper mapper,
            IOrderService orderService,
            IDeviceService deviceService,
            IRepairService repairService,
            IEmployeeService employeeService)
        {
            this.mapper = mapper;
            this.orderService = orderService;
            this.deviceService = deviceService;
            this.repairService = repairService;
            this.employeeService = employeeService;
        }

        [HttpGet]
        public IActionResult CheckOrder()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CheckOrder(CheckOrderViewModel viewModel)
        {
            var order = this.mapper.Map<DataOrderViewModel>(await this.orderService
                .GetOrderAsync(viewModel.OrderNumber, viewModel.OrderPassword));

            if (order == null)
            {
                this.ViewBag.ErrorMessage = "Invalid order number or password";
                return View(viewModel);
            }

            return View(nameof(OrderData), order);
        }

        [HttpPost]
        public IActionResult OrderData(DataOrderViewModel viewModel)
        {
            return View(viewModel);
        }

        [HttpGet]
        [ApplicationAuthentication("Admin", "Receptionist")]
        public async Task<IActionResult> CreateOrder()
        {
            var viewModel = await InitializeCreateOrderViewModelAsync();

            return View(viewModel);
        }

        [HttpPost]
        [ApplicationAuthentication("Admin", "Receptionist")]
        public async Task<IActionResult> CreateOrder(CreateOrderViewModel viewModel) 
        {
            var currentReceptionistId = User
                .FindFirstValue(ClaimTypes.NameIdentifier);

            var order = this.mapper.Map<InsertOrderServiceModel>(viewModel);
            order.ReceptionistId = int.Parse(currentReceptionistId);

            try
            {
                var createdOrderData = await this.orderService.InsertOrderAsync(order);

                var createdOrderViewModel = new CreatedOrderViewModel()
                {
                    OrderNumber = createdOrderData.OrderNumber,
                    OrderPassword = createdOrderData.OrderPassword,
                    OrderPrice = createdOrderData.OrderPrice
                };

                return View("CreatedOrder", createdOrderViewModel);
            }
            catch (Exception)
            {
                this.ViewBag.ErrorMessage = "An error occurred please try again later";
                viewModel = await InitializeCreateOrderViewModelAsync();
                
                return View(viewModel);
            }
        }
        
        [HttpGet]
        [ApplicationAuthentication("Admin", "ServiceWorker")]
        public async Task<IActionResult> RepairOrder()
        {
            var currentserviceWorkerId = User
                .FindFirstValue(ClaimTypes.NameIdentifier);

            var serviceWorkerOrder = await this.orderService.GetServiceWorkerOrderAsync(int.Parse(currentserviceWorkerId));

            var viewModel = this.mapper.Map<RepairOrderViewModel>(serviceWorkerOrder);

            if (viewModel == null)
            {
                return View("ServiceWorkerEmptyOrders");
            }

            return View(viewModel);
        }

        [HttpPost]
        [ApplicationAuthentication("Admin", "ServiceWorker")]
        public async Task<IActionResult> RepairOrder(int OrderId, string repairDescription)
        {
            var currentserviceWorkerId = User
                .FindFirstValue(ClaimTypes.NameIdentifier);

            var insertRepairOrder = new InsertRepairOrderServiceModel()
            {
                OrderId = OrderId,
                RepairDescription = repairDescription,
                ServiceWorkerId = int.Parse(currentserviceWorkerId)
            };

            await this.orderService.InsertRepairOrderAsync(insertRepairOrder);

            return RedirectToAction(nameof(RepairOrder));
        }

        private async Task<CreateOrderViewModel> InitializeCreateOrderViewModelAsync()
        {
            var deviceModels = await this.deviceService.GetAllDeviceModelsAsync();
            var repairTypes = await this.repairService.GetAllRepairTypesAsync();
            var serviceWorkers = await this.employeeService.GetAllServiceWorkers();

            var viewModel = new CreateOrderViewModel();

            foreach (var deviceModel in deviceModels)
            {
                viewModel.DeviceModels
                    .Add(new SelectListItem(deviceModel.DeviceModelName, deviceModel.DeviceModelId.ToString()));
            }

            foreach (var repairType in repairTypes)
            {
                viewModel.RepairTypes
                    .Add(new SelectListItem(repairType.RepairTypeName, repairType.RepairTypeId.ToString()));
            }

            foreach (var serviceWorker in serviceWorkers)
            {
                viewModel.ServiceWorkers
                    .Add(new SelectListItem(serviceWorker.ServiceWorkerName, serviceWorker.ServiceWorkerId.ToString()));
            }

            return viewModel;
        }
    }
}

Source/MobileService/Controllers/ServicesController.cs
namespace MobileService.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class ServicesController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Source/MobileService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MobileService</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top pt-0 pb-0">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Mobile Service</a>
                <button class="navbar-toggler mt-1 mb-1" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav mr-auto">

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Services" asp-action="Index">Services</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Contacts" asp-action="Index">Contacts</a>
                        </li>
                        @if (this.User.IsInRole("Admin") || this.User.IsInRole("Receptionist"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Order" asp-action="CreateOrder">Create Order</a>
                            </li>
                        }
                        @if (this.User.IsInRole("Admin") || this.User.IsInRole("ServiceWorker"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Order" asp-action="RepairOrder">Repair Order</a>
                            </li>
                        }
                        @if (this.User.IsInRole("Admin") || this.User.IsInRole("Receptionist") || this.User.IsInRole("ServiceWorker"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Logout" asp-action="Index">Logout</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item float-right">
                            <a class="nav-link" asp-controller="Order" asp-action="CheckOrder">Check Order</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted text-center" style="background-color: rgb(36, 41, 46);">
        <div class="container">
            &copy; 2020 - Martina Stankova - 46036r
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>